# This is a basic workflow to help you get started with Actions

name: CI\CD


on:
   pull_request:
      branches:
      - 'main'
      types: closed

     
   workflow_dispatch:
    inputs:
      ENVIRONMENT:
        description: Deployment prefix.
        required: true
        type: choice
        options:
          - DEV
          - QA
          - PRD
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  run_if:
    if: github.event.pull_request.closed
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          echo "I'am running"
        
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo test, and deploly your project.
